//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackedGood : TPHRecipe
    {
        public Nullable<decimal> TotalPercentage { get; set; }
        public Nullable<decimal> TotalFat { get; set; }
        public Nullable<decimal> TotalLiquid { get; set; }
    }
}
