//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayHello
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public string MinimumAmount { get; set; }
        public Nullable<int> MinimumUnitID { get; set; }
        public string MaximumAmount { get; set; }
        public Nullable<int> MaximumUnitId { get; set; }
        public string BakersPercentage { get; set; }
        public string Preparation { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Unit MaximumUnit { get; set; }
        public virtual Unit MinimumUnit { get; set; }
    }
}
