//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayHello
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightByUnit
    {
        public int IngredientID { get; set; }
        public int UnitID { get; set; }
        public string Weight { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
